language: node_js
sudo: false
node_js:
  - 7
  - 8
  - node
  - iojs
  - lts/*

before_script:
  - yarn run setup
  - yarn run compile

script:
  - yarn run test

after_success:
  - yarn run docs
  - npm pack