language: node_js
sudo: false
node_js:
  - 7
  - 8
  - node
  - lts/*

before_script:
  - npm install codecov -g

script:
  - yarn run test

after_success:
  - yarn run docs
  - cp .nojekyll
  - npm pack
  - codecov

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN